import numpy as np
from scipy.stats import zscore
import pandas as pd
from scipy.stats import iqr
df = pd.read_csv("DIY Dataset/HRDataset_v14.csv")
print(df.head())
dept_Salary_df = df.groupby(['Department'], as_index=False).Salary.mean()
print(dept_Salary_df)
dept_Salary_df = df.groupby(['Department'], as_index=False).Salary.median()
print(dept_Salary_df)
print("This department has highest number of employees")
print(df['Department'].mode())
print("Department-wise Standard deviation of salary:______")
print(dept_Salary_df['Salary'].std())
print("Department-wise Variance of salary:______")
print(dept_Salary_df['Salary'].var())
print("Inter quartile range of salary:______")
print(iqr(dept_Salary_df['Salary']))
print("Skewness in Original Dataset: __________")
print(df.skew())
print("Kurtosis in Original Dataset: __________")
print(df.kurtosis())
scores = zscore(dept_Salary_df['Salary'])
print("Department-wise z-score of salaries:____________ ")
print(scores)
ptl = np.percentile(df["Salary"], 30)
print("30th percentile of Salary column is:")
print(ptl)
x = np.quantile([20, 40], df["GenderID"])
print("Quartile values of 20, 40 from GenderID column:")
print(x)
